version: "3.8"

services:
  app:
    build: .
    environment:
      helloWorld: "Docker es una chimba"
    volumes: 
      - .:/usr/src/
      - /usr/src/node_modules
    command: npx nodemon -L index.js

  db:
    image: mongo
